services:
  db:
    image: postgis/postgis:18-3.6
    container_name: rowdy-db
    environment:
      POSTGRES_DB: rowdy
      POSTGRES_USER: rowdy
      POSTGRES_PASSWORD: rowdy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: rowdy-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
