"""create organisations

Revision ID: 967e5c0ab97b
Revises: 8c3059a5f3c9
Create Date: 2026-10-04 19:34:11.499258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967e5c0ab97b'
down_revision: Union[str, Sequence[str], None] = '8c3059a5f3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['rowdy.organisations.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['rowdy.venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='rowdy'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events', schema='rowdy')
    # ### end Alembic commands ###
